# Get the list of tasks
GET http://localhost:3000/tasks HTTP/1.1

###
# create a doctor
# The header
POST http://localhost:3000/tasks/ HTTP/1.1
Content-Type: application/json

{
    "title": "Buy groceries",
    "completed": false
}